export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOADING = 'LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

/* tasks  */

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const CATEGORIES = 'CATEGORIES'
export const CATEGORY = 'CATEGORY'
export const TASK_BY_CATEGORY = 'TASKS_BY_CATEGORY'
export const TASKS = 'TASKS'
export const TASK_DETAIL = 'TASK_DETAIL'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const TODAY_TASKS = 'TODAY_TASKS'
export const GET_ALERTS = 'GET_ALERTS'
export const LOADING_CONTENT = 'LOADING_CONTENT'
export const DONE_TASKS = 'DONE_TASKS'
export const MARK_AS_DONE = 'MARK_AS_DONE'
export const MARK_AS_NOT_DONE = 'MARK_AS_NOT_DONE'
